---
- name: Ensure required packages are installed (apt)
  action: apt pkg={{ item }} state=installed
  with_items:
    - git-core
    - build-essential
    - libsqlite3-dev
    - libxslt1-dev
    - libxml2-dev
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev

- name: Get the username of who is running the playbook
  shell: whoami
  register: ruby_whoami

- debug: var=ruby_whoami

- name: Check if Ruby is already installed in /opt/rubies
  stat:
    path: /opt/rubies/ruby-{{ ruby_version }}
  register: ruby_opt
  failed_when: false
  changed_when: false

- debug: var=ruby_opt

- name: Install Ruby with ruby-install
  command: ruby-install ruby {{ ruby_version }}
  when: false
