---
- name: Ensure required packages are installed (apt)
  action: apt pkg={{ item }} state=installed
  become: yes
  with_items:
    - git-core
    - build-essential
    - libsqlite3-dev
    - libxslt1-dev
    - libxml2-dev
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev

- name: Install Ruby with ruby-install
  command: ruby-install --no-reinstall ruby {{ ruby_version }}
  register: ruby_install_output
  changed_when: "'Ruby is already installed into' not in ruby_install_output.stdout"
