---
- name: Ensure required packages are installed (apt)
  become: true
  action: apt pkg={{ item }} state=installed
  with_items:
    - git-core
    - build-essential
    - libsqlite3-dev
    - libxslt1-dev
    - libxml2-dev
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev

- name: Get the username of who is running the playbook
  local_action: command whoami
  become: no
  register: remote_user
  changed_when: false

- name: Ensure Ruby is installed
  stat:
    path: /home/{{ remote_user.stdout }}/.rubies/ruby-{{ ruby_version }}
  register: ruby_gem_stat

- name: Install Ruby with ruby-install
  command: ruby-install ruby {{ ruby_version }}
  when: ruby_gem_stat.stat.exists == False
